### ISSUE TITLE
Expected value of dice roll is 3.5, not 3 (question 6)

### ISSUE THREAD

**Issue by c45** [adijo/data-science-prep#1]
In Question 6 – Picking between two dice games, you state the expected value E[X] of a dice roll (X ∼ Uniform(1, 6)) is 3, when it is actually 3.5. This results in a very different expected value for E[XY] of 3.5 * 3.5 = 12.25 and E[Z^2] = 2.92 + 12.25 = 15.17.

Other than that, I enjoyed reading through your solutions. Cheers!

**Comment by adijo** [comment]
I just saw this. Thanks a lot @kyang8093 for taking the time to point this out. I've corrected this and credited you in the solution!
