### ISSUE TITLE
Q21 in pdf

### ISSUE THREAD

**Issue by sarvepalli18** [adijo/data-science-prep#4]
The total number of possibilities was considered as 8-1 =7

But why will the order matter here, isn't 101, 110 and 011 the same ?

I think there are three possibilities that contain at least one fan viz (fan, not fan, not fan), (fan, fan, not fan) and (fan, fan, fan)

out of these only one combination has exactly one fan, so probability is 1/3

**Comment by adijo** [comment]
The three options represent the three people, `p_1`, `p_2` and `p_3.` (`p_1 = 1, p_2 = 0, p_3 = 1` and `p_1 = 1, p_2 = 1, p_3 = 0` are not the same)
